@startuml
interface Sensor {
        +getReading(): double
    }
    class TemperatureSensor {
    }
    class LightSensor {
    }
    class MotionSensor {
    }
    interface Actuator {
        +performAction(): void
    }
    class Thermostat {
        -currentTemperature: double
        -desiredTemperature: double
    }
    class LightBulb {
        -isOpen: boolean
    }
    class DoorLock {
        -isLocked: boolean
    }
interface ControlPanel {
    +setTemperature(int desiredTemp): void
    +openLights(): void
    +closeLights(): void
    +lockTheDoor(): void
    +unlockTheDoor(): void
    +setMediator(Mediator mediator): void
}
class UserControlPanel {
}
interface SmartHome {
    -temperatureSensor: TemperatureSensor
    -lightSensor: LightSensor
    -motionSensor: MotionSensor
    -thermostat: Thermostat
    -lightBulb: LightBulb
    -doorLock: DoorLock
    +regulateTemperature: void
    +regulateLightBulb: void
    +regulateDoorLock: void
    +updateTemperature: void
    +updateLights: void
    +updateDoor: void
}
class User {
   -controlPanel: ControlPanel
   +updateTemperature(int desiredTemp): void
   +openLights(): void
   +closeLights(): void
   +lockTheDoor(): void
   +unlockTheDoor(): void
}

ControlPanel o-- SmartHome
Sensor --o  SmartHome
Actuator --o SmartHome
Sensor <|-- TemperatureSensor
Sensor <|-- LightSensor
Sensor <|-- MotionSensor
Thermostat  --|>  Actuator
LightBulb  --|>   Actuator
DoorLock  --|> Actuator
ControlPanel <|--  UserControlPanel
User o-- ControlPanel
@enduml