@startuml
participant TemperatureSensor order 200
participant SmartHome order 100
participant Thermostat order 300
participant Display order 500

SmartHome -> SmartHome: currentTemperature\n (decided randomly)
SmartHome -> TemperatureSensor: setTemperature(int currTemp)
alt 20 <= currentTemperature <= 25
SmartHome -> Display: No action required
else
    loop currentTemperature > 25 || currentTemperature < 20
    SmartHome -> Thermostat: performAction(int currTemp)
    Thermostat -> SmartHome: int updatedTemp
    SmartHome -> TemperatureSensor: setTemperature(int updatedTemp)
    TemperatureSensor -> Display: Displays updated temp
    end
end
@enduml